//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/philippgrigoryev/projects/reporting-tool/reporting-tool/BoolExpr/BoolExpr.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BoolExprParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IBoolExprListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>andExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExp([NotNull] BoolExprParser.AndExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>andExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExp([NotNull] BoolExprParser.AndExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>attrPrExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrPrExp([NotNull] BoolExprParser.AttrPrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>attrPrExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrPrExp([NotNull] BoolExprParser.AttrPrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parenthesisExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesisExp([NotNull] BoolExprParser.ParenthesisExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenthesisExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesisExp([NotNull] BoolExprParser.ParenthesisExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>attrCompExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrCompExp([NotNull] BoolExprParser.AttrCompExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>attrCompExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrCompExp([NotNull] BoolExprParser.AttrCompExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>orExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExp([NotNull] BoolExprParser.OrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>orExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExp([NotNull] BoolExprParser.OrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>notExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExp([NotNull] BoolExprParser.NotExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExp([NotNull] BoolExprParser.NotExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BoolExprParser.attr_comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttr_comp([NotNull] BoolExprParser.Attr_compContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BoolExprParser.attr_comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttr_comp([NotNull] BoolExprParser.Attr_compContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BoolExprParser.attr_pr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttr_pr([NotNull] BoolExprParser.Attr_prContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BoolExprParser.attr_pr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttr_pr([NotNull] BoolExprParser.Attr_prContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>profileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProfileAttr([NotNull] BoolExprParser.ProfileAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>profileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProfileAttr([NotNull] BoolExprParser.ProfileAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>nonProfileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonProfileAttr([NotNull] BoolExprParser.NonProfileAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>nonProfileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonProfileAttr([NotNull] BoolExprParser.NonProfileAttrContext context);
}
