//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/philippgrigoryev/projects/reporting-tool/reporting-tool/BoolExpr/BoolExpr.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBoolExprListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class BoolExprBaseListener : IBoolExprListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>andExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExp([NotNull] BoolExprParser.AndExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>andExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExp([NotNull] BoolExprParser.AndExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>attrPrExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrPrExp([NotNull] BoolExprParser.AttrPrExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>attrPrExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrPrExp([NotNull] BoolExprParser.AttrPrExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parenthesisExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesisExp([NotNull] BoolExprParser.ParenthesisExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parenthesisExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesisExp([NotNull] BoolExprParser.ParenthesisExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>attrCompExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrCompExp([NotNull] BoolExprParser.AttrCompExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>attrCompExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrCompExp([NotNull] BoolExprParser.AttrCompExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>orExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExp([NotNull] BoolExprParser.OrExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>orExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExp([NotNull] BoolExprParser.OrExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>notExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExp([NotNull] BoolExprParser.NotExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>notExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExp([NotNull] BoolExprParser.NotExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BoolExprParser.attr_comp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttr_comp([NotNull] BoolExprParser.Attr_compContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BoolExprParser.attr_comp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttr_comp([NotNull] BoolExprParser.Attr_compContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BoolExprParser.attr_pr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttr_pr([NotNull] BoolExprParser.Attr_prContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BoolExprParser.attr_pr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttr_pr([NotNull] BoolExprParser.Attr_prContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>profileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProfileAttr([NotNull] BoolExprParser.ProfileAttrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>profileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProfileAttr([NotNull] BoolExprParser.ProfileAttrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>nonProfileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonProfileAttr([NotNull] BoolExprParser.NonProfileAttrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>nonProfileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonProfileAttr([NotNull] BoolExprParser.NonProfileAttrContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
