//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/philippgrigoryev/projects/reporting-tool/reporting-tool/BoolExpr/BoolExpr.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BoolExprParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IBoolExprVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>andExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExp([NotNull] BoolExprParser.AndExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>attrPrExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrPrExp([NotNull] BoolExprParser.AttrPrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExp([NotNull] BoolExprParser.ParenthesisExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>attrCompExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrCompExp([NotNull] BoolExprParser.AttrCompExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>orExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExp([NotNull] BoolExprParser.OrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notExp</c>
	/// labeled alternative in <see cref="BoolExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExp([NotNull] BoolExprParser.NotExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>eqCompare</c>
	/// labeled alternative in <see cref="BoolExprParser.attr_comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqCompare([NotNull] BoolExprParser.EqCompareContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>coCompare</c>
	/// labeled alternative in <see cref="BoolExprParser.attr_comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCoCompare([NotNull] BoolExprParser.CoCompareContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>swCompare</c>
	/// labeled alternative in <see cref="BoolExprParser.attr_comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwCompare([NotNull] BoolExprParser.SwCompareContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ewCompare</c>
	/// labeled alternative in <see cref="BoolExprParser.attr_comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEwCompare([NotNull] BoolExprParser.EwCompareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BoolExprParser.attr_pr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttr_pr([NotNull] BoolExprParser.Attr_prContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>profileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProfileAttr([NotNull] BoolExprParser.ProfileAttrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nonProfileAttr</c>
	/// labeled alternative in <see cref="BoolExprParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonProfileAttr([NotNull] BoolExprParser.NonProfileAttrContext context);
}
