name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout custom okta-sdk-dotnet
      uses: actions/checkout@v2
      with:
          repository: 'phi1ipp/okta-sdk-dotnet'   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build custom SDK
      run: cd src/Okta.Sdk && dotnet package
    - uses: actions/checkout@v1
